// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npzxrwegjfvpxvojinpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wenhyd2VnamZ2cHh2b2ppbnBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDU1NzIsImV4cCI6MjA2NDc4MTU3Mn0.DoEFurVmAP0_GSL8DAbvgiFF8lj469XkKIQLzlAnf8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);